name: FloralAPI
main: me.lilac.floralapi.plugin.FloralAPI
version: 1.0.0
api-version: 1.15
description: A testing plugin for FloralAPI.
author: Lilac
softdepend: [Vault, PlaceholderAPI]
commands:
  floralapi:
    aliases: [floral]
    description: Main command for FloralAPI.
permissions:
  floralapi.*:
    default: op
    children:
      - floralapi.use
  floralapi.use:
    description: Allows a player to use /floral.
    default: op