name: FloralAPI
main: me.lilac.floralapi.FloralPlugin
version: 1.0.0
api-version: 1.14
description: A testing plugin for FloralAPI.
author: Lilac
softdepend: [Vault, PlaceholderAPI]
commands:
  command:
    aliases: [cmd]
    description: Main command for FloralAPI.
permissions:
  command.*:
    default: op
    children:
      - command.use
  command.use:
    description: Allows a player to use /command.
    default: op