name: FloralAPI
main: me.lilac.floralapi.Example
version: 1.0.0
api-version: 1.15
description: A testing plugin for FloralAPI.
author: Lilac
softdepend: [Vault, PlaceholderAPI]
commands:
  floral:
    description: Main command for FloralAPI example.
    aliases: [floralapi]
permissions:
  floralapi.*:
    default: op
    children:
      - floralapi.use
  floralapi.use:
    description: Allows a player to use /floral.
    default: op